//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AS_DBEntities : DbContext
    {
        public AS_DBEntities()
            : base("name=AS_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TB_Area> TB_Area { get; set; }
        public virtual DbSet<TB_CenterMeter> TB_CenterMeter { get; set; }
        public virtual DbSet<TB_Collector> TB_Collector { get; set; }
        public virtual DbSet<TB_Customer> TB_Customer { get; set; }
        public virtual DbSet<TB_Cycle> TB_Cycle { get; set; }
        public virtual DbSet<TB_Meter> TB_Meter { get; set; }
        public virtual DbSet<TB_Read> TB_Read { get; set; }
        public virtual DbSet<TB_Receipt> TB_Receipt { get; set; }
        public virtual DbSet<TB_Subscription> TB_Subscription { get; set; }
        public virtual DbSet<TB_User> TB_User { get; set; }
        public virtual DbSet<View_Bill> View_Bill { get; set; }
        public virtual DbSet<TB_LogCustomer> TB_LogCustomer { get; set; }
        public virtual DbSet<View_Customer> View_Customer { get; set; }
        public virtual DbSet<TB_Block> TB_Block { get; set; }
    }
}
