//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Block
    {
        public int block_id { get; set; }
        public string block_name { get; set; }
        public Nullable<int> area_id { get; set; }
        public Nullable<int> coll_id { get; set; }
    
        public virtual TB_Area TB_Area { get; set; }
        public virtual TB_Collector TB_Collector { get; set; }
    }
}
