//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Customer()
        {
            this.TB_Receipt = new HashSet<TB_Receipt>();
        }
    
        public int cust_id { get; set; }
        public Nullable<int> meter_id { get; set; }
        public string cust_name { get; set; }
        public string cust_address { get; set; }
        public Nullable<int> cust_phone { get; set; }
        public string activity { get; set; }
        public byte[] cust_card { get; set; }
        public Nullable<double> balance { get; set; }
        public Nullable<int> area_id { get; set; }
    
        public virtual TB_Meter TB_Meter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Receipt> TB_Receipt { get; set; }
    }
}
