//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CenterMeter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_CenterMeter()
        {
            this.TB_Meter = new HashSet<TB_Meter>();
        }
    
        public int centerMeter_id { get; set; }
        public Nullable<int> centerMeter_no { get; set; }
        public Nullable<int> area_id { get; set; }
        public Nullable<int> number_meters { get; set; }
    
        public virtual TB_Area TB_Area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Meter> TB_Meter { get; set; }
    }
}
