//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_LogCustomer
    {
        public int log_id { get; set; }
        public Nullable<int> meter_id { get; set; }
        public string bill_type { get; set; }
        public Nullable<int> bill_no { get; set; }
        public Nullable<double> cust_debtor { get; set; }
        public Nullable<double> cust_Creditor { get; set; }
        public Nullable<double> cust_balance { get; set; }
        public Nullable<System.DateTime> log_date { get; set; }
    
        public virtual TB_Meter TB_Meter { get; set; }
    }
}
