//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Read
    {
        public int read_id { get; set; }
        public int meter_id { get; set; }
        public Nullable<int> cycle_id { get; set; }
        public Nullable<double> pre_read { get; set; }
        public Nullable<double> current_read { get; set; }
        public Nullable<double> consume { get; set; }
        public Nullable<double> consume_price { get; set; }
        public Nullable<System.DateTime> date_read { get; set; }
        public Nullable<double> later_price { get; set; }
    
        public virtual TB_Cycle TB_Cycle { get; set; }
        public virtual TB_Meter TB_Meter { get; set; }
    }
}
