//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Receipt
    {
        public int receipt_id { get; set; }
        public Nullable<int> receipt_no { get; set; }
        public Nullable<int> cust_id { get; set; }
        public Nullable<int> coll_id { get; set; }
        public Nullable<double> money { get; set; }
        public Nullable<System.DateTime> receipt_date { get; set; }
        public string detail { get; set; }
    
        public virtual TB_Collector TB_Collector { get; set; }
        public virtual TB_Customer TB_Customer { get; set; }
    }
}
