//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Customer
    {
        public int cust_id { get; set; }
        public string اسم_المشترك { get; set; }
        public Nullable<int> رقم_العداد { get; set; }
        public string العنوان { get; set; }
        public Nullable<int> الجوال { get; set; }
        public Nullable<double> آخر_قراءة { get; set; }
        public Nullable<double> الرصيد { get; set; }
        public Nullable<bool> الحالة { get; set; }
    }
}
