//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Bill
    {
        public string اسم_المشترك { get; set; }
        public int meter_id { get; set; }
        public Nullable<int> رقم_العداد { get; set; }
        public string العنوان { get; set; }
        public string الاشتراك { get; set; }
        public string النشاط { get; set; }
        public int cycle_id { get; set; }
        public string رقم_الدورة { get; set; }
        public Nullable<double> القراءة_السابقة { get; set; }
        public Nullable<double> القراءة_الحالية { get; set; }
        public Nullable<double> الإستهلاك { get; set; }
        public Nullable<double> المبلغ { get; set; }
        public Nullable<double> المتأخرات { get; set; }
        public Nullable<double> الحد_الأدنى { get; set; }
        public Nullable<double> إجمالي_المبلغ { get; set; }
        public Nullable<System.DateTime> تاريخ_القراءة { get; set; }
    }
}
